// src/utils/errorCodes.ts
export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  INVALID_INPUT: "INVALID_INPUT",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR:"VALIDATION_ERROR",
  INVALID_TOKEN:"INVALID_TOKEN",
  USER_EXISTS:"USER_EXISTS",
  INVALID_OTP:"INVALID_OTP",
  USER_NOT_FOUND:"USER_NOT_FOUND",
  EMAIL_NOT_VERIFIED:"EMAIL_NOT_VERIFIED",
  INVALID_CREDENTIALS:"INVALID_CREDENTIALS",
  EMAIL_ALREADY_VERIFIED:"EMAIL_ALREADY_VERIFIED"
} as const;
